import { usePreferences } from "./context";

const messages = {
  en: {
    openBudgetMap: "Open Budget Map", budgetInsights: "Budget Insights", contractors: "Contractors", watchdog: "Watchdog", chatBot: "ChatBot", api: "API", settings: "Settings",
    collapseSidebar: "Collapse sidebar", openNavigation: "Open navigation", closeNavigation: "Close navigation", quickPreferences: "Quick preferences", selectLanguage: "Select language", switchToDarkMode: "Switch to dark mode", switchToLightMode: "Switch to light mode",
    settingsIntro: "Customize how Open Budget Nepal appears on this device.", language: "Language", languageHelp: "Choose the language used for supported interface labels.",
    appearance: "Appearance", appearanceHelp: "Use your device setting or choose a fixed appearance.", system: "System", light: "Light", dark: "Dark",
    resetPreferences: "Reset preferences", resetHelp: "Restore language and appearance to their defaults.", resetToDefaults: "Reset to defaults", english: "English", nepali: "नेपाली",
    mapIntro: "Explore Nepal by province and local government, then open the available budget context.", nepal: "Nepal", province: "Province", localLevel: "Local Level", allNepal: "All Nepal", allLocalLevels: "All local levels", selectProvinceFirst: "Select a province first", loadingBoundaries: "Loading local boundaries…", boundaryLoadError: "Administrative boundaries could not be loaded.", returnToNepal: "Return to Nepal", provincialBudgetContext: "Provincial revenue, grants and expenditure.", localBudgetContext: "Local revenue, transfers and expenditure.", availableProjectBudget: "Available project budget", exploreInsights: "Explore insights", fiscalYearShort: "FY", budgetContextFor: "Budget context for", overview: "Overview", nationalSnapshot: "National snapshot", federal: "Federal", nationalAccounts: "National accounts", provincial: "Provincial", sevenGovernments: "7 governments", local: "Local", localLevelCount: "753 local levels", consolidatedBudget: "Consolidated budget", actualExpenditure: "Actual expenditure", utilization: "Utilization", revenueTrend: "Revenue trend", nprBillionsBs: "NPR billions · B.S.", revenue: "Revenue", expenditure: "Expenditure", budgetInsightSections: "Budget insight sections",
    contractorsDirectory: "Contractors directory", contractorsDirectoryIntro: "Search public contract recipients by legal name or PAN, then inspect their awards and joint ventures.", searchAndFilters: "Search and filters", contractorName: "Contractor name", searchContractorName: "Search contractor name", searchPan: "Search PAN", allContractCategories: "All contract categories", allContractFiscalYears: "All contract fiscal years", nameAz: "Name A–Z", nameZa: "Name Z–A", contractorRecords: "contractor records", publicProcurementRecords: "Public procurement records", loadingContractors: "Loading contractors", contractorApiError: "The contractor API could not be reached. Confirm the backend is running and try again.", noContractors: "No contractors match these filters", noContractorsHelp: "Try a shorter name, remove the PAN, or clear a filter.", serialNumber: "S.N.", contractor: "Contractor", pan: "PAN", contractCategories: "Contract categories", contracts: "Contracts", awardedValue: "Awarded value", countryNotProvided: "Country not provided", notProvided: "Not provided", notClassified: "Not classified", previous: "Previous", next: "Next", page: "Page", contractorDirectoryPages: "Contractor directory pages",
    watchdogTitle: "Suspicious Activity Watchdog", watchdogIntro: "Rule-based procurement monitoring using available public contract records.", monitoredProjects: "Monitored projects", acrossFiscalYears: "across available fiscal years", triggeredFindings: "Triggered findings", highSeverity: "High severity", markedFollowUp: "Marked for follow-up", reviewSession: "in this review session", searchWatchdog: "Search watchdog findings", searchWatchdogPlaceholder: "Search contractor, project, or finding", filterRule: "Filter by rule", filterSeverity: "Filter by severity", filterAssessment: "Filter by assessment status", filterFiscalYear: "Filter by fiscal year", allTypes: "All Types", allRules: "All rules", severeDelay: "Severe Delay", costOverrun: "Cost Overrun", highConcentration: "High Concentration", allSeverities: "All Severities", high: "High", medium: "Medium", allProjects: "All projects", scoredFindings: "Findings only", inheritedRisk: "Inherited contractor risk", noFinding: "No finding", insufficientData: "Insufficient data", allFiscalYears: "All fiscal years", loadingProjects: "Loading projects…", showing: "Showing", of: "of", projects: "projects", findings: "findings", watchdogLoadError: "Watchdog findings could not be loaded.", riskScore: "Risk score", rule: "Rule", severity: "Severity", project: "Project", fiscalYear: "Fiscal year", finding: "Finding", actions: "Actions", inherited: "Inherited", clear: "Clear", notEvaluated: "Not evaluated", flag: "Flag", feedback: "Feedback", view: "View", noProjects: "No projects match these filters", noProjectsHelp: "Try changing the assessment status, rule, severity, fiscal year, or search.", watchdogPages: "Watchdog findings pages",
    chatTitle: "Open Budget Assistant", chatIntro: "Ask questions about Nepal's public budget, projects, procurement, and related records.", chatEmptyTitle: "Ask about Nepal's public finances", chatEmptyIntro: "Explore budget, project, procurement, and contractor records through one focused conversation.", chatPromptBudgets: "Compare annual budgets", chatPromptProjects: "Find infrastructure projects", chatPromptContractors: "Explore contractor awards", chatPromptWatchdog: "Explain a Watchdog finding", chatInputLabel: "Message Open Budget Assistant", chatInputPlaceholder: "Ask about budgets, projects, contractors, or procurement…", sendMessage: "Send message", chatContext: "Context", viewChatContext: "View context", chatSources: "Relevant sources", chatNoSources: "No sources loaded yet", chatConversation: "Conversation", chatNewConversation: "New conversation", chatScope: "Scope",
    apiPublicInterface: "Public data interface", apiTitle: "Open Budget Nepal API", apiIntro: "Public, read-only access to Nepal budget, procurement and transparency data. No account or API key is required.", openApiDocs: "Open interactive API docs", openApiJson: "OpenAPI JSON", baseUrl: "Base URL", amountNote: "Amounts are raw decimal strings in NPR. Missing values are null, never fabricated zeroes.", quickStart: "Quick start", quickStartHelp: "Request ten available project records for fiscal year 2081/82.", copyCurl: "Copy cURL request", copied: "Copied", copy: "Copy", availableResources: "Available resources", budgets: "Budgets", procurement: "Procurement", watchdogFindings: "Watchdog", commonParameters: "Common parameters", responseShape: "Response shape", rateLimitNote: "Requests are limited to 120 per minute per client IP. Pagination is performed by the database.", budgetResource: "Federal budget and actual amounts by available classification.", projectResource: "Project and programme records kept distinct from awarded contracts.", contractorResource: "Factual contractor profiles and linked contract histories.", procurementResource: "Procurement-classified award records available in the database.", contractResource: "Awarded contract amounts, entities, dates and contractors.", watchdogResource: "Deterministic findings with rule evidence and methodology.", searchFields: "Search supported text fields", pageNumber: "Page number, starting at 1", resultsPerPage: "Results per page, maximum 100", fiscalYearParameter: "Nepali fiscal year, such as 2081/82", sortParameter: "Endpoint-specific whitelisted order", provinceRegistry: "Official administrative registry ID", districtRegistry: "District registry ID", municipalityRegistry: "Local-level registry ID",
  },
  ne: {
    openBudgetMap: "खुला बजेट नक्सा", budgetInsights: "बजेट विश्लेषण", contractors: "निर्माण व्यवसायी", watchdog: "निगरानी", chatBot: "च्याटबट", api: "एपीआई", settings: "सेटिङहरू",
    collapseSidebar: "साइडबार खुम्च्याउनुहोस्", openNavigation: "नेभिगेसन खोल्नुहोस्", closeNavigation: "नेभिगेसन बन्द गर्नुहोस्", quickPreferences: "द्रुत प्राथमिकताहरू", selectLanguage: "भाषा छान्नुहोस्", switchToDarkMode: "गाढा रूपमा बदल्नुहोस्", switchToLightMode: "उज्यालो रूपमा बदल्नुहोस्",
    settingsIntro: "यस उपकरणमा Open Budget Nepal कसरी देखिन्छ भन्ने रोज्नुहोस्।", language: "भाषा", languageHelp: "समर्थित इन्टरफेस लेबलहरूको भाषा रोज्नुहोस्।",
    appearance: "रूप", appearanceHelp: "उपकरणको सेटिङ प्रयोग गर्नुहोस् वा निश्चित रूप रोज्नुहोस्।", system: "प्रणाली", light: "उज्यालो", dark: "गाढा",
    resetPreferences: "प्राथमिकता रिसेट", resetHelp: "भाषा र रूपलाई पूर्वनिर्धारित अवस्थामा फर्काउनुहोस्।", resetToDefaults: "पूर्वनिर्धारितमा फर्काउनुहोस्", english: "English", nepali: "नेपाली",
    mapIntro: "प्रदेश र स्थानीय सरकारअनुसार नेपाल हेर्नुहोस् र उपलब्ध बजेट विवरण खोल्नुहोस्।", nepal: "नेपाल", province: "प्रदेश", localLevel: "स्थानीय तह", allNepal: "सम्पूर्ण नेपाल", allLocalLevels: "सबै स्थानीय तह", selectProvinceFirst: "पहिले प्रदेश छान्नुहोस्", loadingBoundaries: "स्थानीय सीमा लोड हुँदैछ…", boundaryLoadError: "प्रशासनिक सीमा लोड गर्न सकिएन।", returnToNepal: "नेपालमा फर्कनुहोस्", provincialBudgetContext: "प्रदेशको राजस्व, अनुदान र खर्च।", localBudgetContext: "स्थानीय राजस्व, हस्तान्तरण र खर्च।", availableProjectBudget: "उपलब्ध आयोजना बजेट", exploreInsights: "बजेट विश्लेषण हेर्नुहोस्", fiscalYearShort: "आ.व.", budgetContextFor: "बजेट विवरण", overview: "समग्र विवरण", nationalSnapshot: "राष्ट्रिय संक्षिप्त विवरण", federal: "संघीय", nationalAccounts: "राष्ट्रिय लेखा", provincial: "प्रदेश", sevenGovernments: "७ सरकार", local: "स्थानीय", localLevelCount: "७५३ स्थानीय तह", consolidatedBudget: "एकीकृत बजेट", actualExpenditure: "वास्तविक खर्च", utilization: "उपयोग", revenueTrend: "राजस्व प्रवृत्ति", nprBillionsBs: "रु. अर्ब · वि.सं.", revenue: "राजस्व", expenditure: "खर्च", budgetInsightSections: "बजेट विश्लेषण खण्डहरू",
    contractorsDirectory: "निर्माण व्यवसायी निर्देशिका", contractorsDirectoryIntro: "कानुनी नाम वा प्यानबाट सार्वजनिक ठेक्का प्राप्तकर्ता खोज्नुहोस् र तिनका ठेक्का तथा संयुक्त उपक्रम हेर्नुहोस्।", searchAndFilters: "खोज र फिल्टर", contractorName: "निर्माण व्यवसायीको नाम", searchContractorName: "निर्माण व्यवसायीको नाम खोज्नुहोस्", searchPan: "प्यान खोज्नुहोस्", allContractCategories: "सबै ठेक्का वर्ग", allContractFiscalYears: "सबै ठेक्का आर्थिक वर्ष", nameAz: "नाम क–ज्ञ", nameZa: "नाम ज्ञ–क", contractorRecords: "निर्माण व्यवसायी अभिलेख", publicProcurementRecords: "सार्वजनिक खरिद अभिलेख", loadingContractors: "निर्माण व्यवसायी लोड हुँदैछ", contractorApiError: "निर्माण व्यवसायी एपीआईमा सम्पर्क हुन सकेन। ब्याकएन्ड चलिरहेको छ कि जाँच गरी फेरि प्रयास गर्नुहोस्।", noContractors: "यी फिल्टरसँग मिल्ने निर्माण व्यवसायी छैनन्", noContractorsHelp: "छोटो नाम प्रयोग गर्नुहोस्, प्यान हटाउनुहोस् वा फिल्टर खाली गर्नुहोस्।", serialNumber: "क्र.सं.", contractor: "निर्माण व्यवसायी", pan: "प्यान", contractCategories: "ठेक्का वर्ग", contracts: "ठेक्का", awardedValue: "प्रदान गरिएको मूल्य", countryNotProvided: "देश उपलब्ध छैन", notProvided: "उपलब्ध छैन", notClassified: "वर्गीकृत छैन", previous: "अघिल्लो", next: "अर्को", page: "पृष्ठ", contractorDirectoryPages: "निर्माण व्यवसायी निर्देशिका पृष्ठहरू",
    watchdogTitle: "शंकास्पद गतिविधि निगरानी", watchdogIntro: "उपलब्ध सार्वजनिक ठेक्का अभिलेखमा आधारित नियमगत खरिद निगरानी।", monitoredProjects: "अनुगमन गरिएका आयोजना", acrossFiscalYears: "उपलब्ध आर्थिक वर्षहरूमा", triggeredFindings: "देखिएका निष्कर्ष", highSeverity: "उच्च गम्भीरता", markedFollowUp: "पुनरावलोकनका लागि चिन्हित", reviewSession: "यस समीक्षा सत्रमा", searchWatchdog: "निगरानी निष्कर्ष खोज्नुहोस्", searchWatchdogPlaceholder: "निर्माण व्यवसायी, आयोजना वा निष्कर्ष खोज्नुहोस्", filterRule: "नियमअनुसार फिल्टर", filterSeverity: "गम्भीरताअनुसार फिल्टर", filterAssessment: "मूल्याङ्कन अवस्थाअनुसार फिल्टर", filterFiscalYear: "आर्थिक वर्षअनुसार फिल्टर", allTypes: "सबै प्रकार", allRules: "सबै नियम", severeDelay: "गम्भीर ढिलाइ", costOverrun: "लागत वृद्धि", highConcentration: "उच्च केन्द्रीकरण", allSeverities: "सबै गम्भीरता", high: "उच्च", medium: "मध्यम", allProjects: "सबै आयोजना", scoredFindings: "निष्कर्ष मात्र", inheritedRisk: "निर्माण व्यवसायीबाट आएको जोखिम", noFinding: "निष्कर्ष छैन", insufficientData: "अपर्याप्त तथ्याङ्क", allFiscalYears: "सबै आर्थिक वर्ष", loadingProjects: "आयोजना लोड हुँदैछ…", showing: "देखाइएको", of: "मध्ये", projects: "आयोजना", findings: "निष्कर्ष", watchdogLoadError: "निगरानी निष्कर्ष लोड हुन सकेन।", riskScore: "जोखिम अंक", rule: "नियम", severity: "गम्भीरता", project: "आयोजना", fiscalYear: "आर्थिक वर्ष", finding: "निष्कर्ष", actions: "कार्य", inherited: "सम्बद्ध", clear: "सफा", notEvaluated: "मूल्याङ्कन नभएको", flag: "चिन्ह लगाउनुहोस्", feedback: "प्रतिक्रिया", view: "हेर्नुहोस्", noProjects: "यी फिल्टरसँग मिल्ने आयोजना छैनन्", noProjectsHelp: "मूल्याङ्कन अवस्था, नियम, गम्भीरता, आर्थिक वर्ष वा खोज परिवर्तन गर्नुहोस्।", watchdogPages: "निगरानी निष्कर्ष पृष्ठहरू",
    chatTitle: "खुला बजेट सहायक", chatIntro: "नेपालको सार्वजनिक बजेट, आयोजना, खरिद र सम्बन्धित अभिलेखबारे प्रश्न सोध्नुहोस्।", chatEmptyTitle: "नेपालको सार्वजनिक वित्तबारे सोध्नुहोस्", chatEmptyIntro: "एउटै केन्द्रित संवादबाट बजेट, आयोजना, खरिद र निर्माण व्यवसायी अभिलेख खोज्नुहोस्।", chatPromptBudgets: "वार्षिक बजेट तुलना गर्नुहोस्", chatPromptProjects: "पूर्वाधार आयोजना खोज्नुहोस्", chatPromptContractors: "निर्माण व्यवसायीका ठेक्का हेर्नुहोस्", chatPromptWatchdog: "निगरानी निष्कर्ष व्याख्या गर्नुहोस्", chatInputLabel: "खुला बजेट सहायकलाई सन्देश", chatInputPlaceholder: "बजेट, आयोजना, निर्माण व्यवसायी वा खरिदबारे सोध्नुहोस्…", sendMessage: "सन्देश पठाउनुहोस्", chatContext: "सन्दर्भ", viewChatContext: "सन्दर्भ हेर्नुहोस्", chatSources: "सम्बन्धित स्रोत", chatNoSources: "अहिलेसम्म स्रोत लोड भएको छैन", chatConversation: "संवाद", chatNewConversation: "नयाँ संवाद", chatScope: "दायरा",
    apiPublicInterface: "सार्वजनिक तथ्याङ्क इन्टरफेस", apiTitle: "Open Budget Nepal एपीआई", apiIntro: "नेपालको बजेट, खरिद र पारदर्शिता तथ्याङ्कमा सार्वजनिक, पढ्न-मात्र पहुँच। खाता वा एपीआई कुञ्जी आवश्यक छैन।", openApiDocs: "अन्तरक्रियात्मक एपीआई दस्तावेज खोल्नुहोस्", openApiJson: "OpenAPI JSON", baseUrl: "आधार URL", amountNote: "रकमहरू NPR मा कच्चा दशमलव स्ट्रिङका रूपमा छन्। उपलब्ध नभएका मान null हुन्छन्, बनावटी शून्य होइनन्।", quickStart: "द्रुत सुरुवात", quickStartHelp: "आर्थिक वर्ष २०८१/८२ का उपलब्ध दश आयोजना अभिलेख माग्नुहोस्।", copyCurl: "cURL अनुरोध प्रतिलिपि गर्नुहोस्", copied: "प्रतिलिपि भयो", copy: "प्रतिलिपि", availableResources: "उपलब्ध स्रोतहरू", budgets: "बजेट", procurement: "खरिद", watchdogFindings: "निगरानी", commonParameters: "साझा प्यारामिटर", responseShape: "प्रतिक्रिया संरचना", rateLimitNote: "प्रति क्लाइन्ट आईपी प्रति मिनेट १२० अनुरोध सीमित छन्। पृष्ठ विभाजन डाटाबेसबाट हुन्छ।", budgetResource: "उपलब्ध वर्गीकरणअनुसार संघीय बजेट र वास्तविक रकम।", projectResource: "प्रदान गरिएका ठेक्काभन्दा अलग राखिएका आयोजना तथा कार्यक्रम अभिलेख।", contractorResource: "तथ्यगत निर्माण व्यवसायी विवरण र सम्बन्धित ठेक्का इतिहास।", procurementResource: "डाटाबेसमा उपलब्ध खरिद-वर्गीकृत ठेक्का अभिलेख।", contractResource: "प्रदान गरिएको ठेक्का रकम, निकाय, मिति र निर्माण व्यवसायी।", watchdogResource: "नियम प्रमाण र विधिसहितका निर्धारित निष्कर्ष।", searchFields: "समर्थित पाठ फिल्ड खोज्नुहोस्", pageNumber: "१ बाट सुरु हुने पृष्ठ सङ्ख्या", resultsPerPage: "प्रति पृष्ठ नतिजा, अधिकतम १००", fiscalYearParameter: "नेपाली आर्थिक वर्ष, जस्तै २०८१/८२", sortParameter: "एन्डपोइन्टअनुसार स्वीकृत क्रम", provinceRegistry: "आधिकारिक प्रदेश दर्ता आईडी", districtRegistry: "जिल्ला दर्ता आईडी", municipalityRegistry: "स्थानीय तह दर्ता आईडी",
  },
} as const;

export type MessageKey = keyof typeof messages.en;
export function useTranslation() {
  const { preferences } = usePreferences();
  return (key: MessageKey) => messages[preferences.language][key];
}
