import { useEffect,useState } from "react";
import { ArrowLeft } from "lucide-react";
import { Link,useParams } from "react-router-dom";
import Layout from "@/components/layout/Layout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { getContract,type ContractDetail } from "@/features/contractors/api/contractorDirectoryApi";
const money=(value:number)=>new Intl.NumberFormat("en-NP",{style:"currency",currency:"NPR",maximumFractionDigits:2}).format(value);
export default function ContractDetailPage(){const {id=""}=useParams();const [data,setData]=useState<ContractDetail|null>(null);const [error,setError]=useState(false);useEffect(()=>{const controller=new AbortController();getContract(id,controller.signal).then(setData).catch(()=>setError(true));return()=>controller.abort()},[id]);if(error)return <Layout><State text="Contract details could not be loaded."/></Layout>;if(!data)return <Layout><State text="Loading contract details…"/></Layout>;const fields:[[string,unknown],[string,unknown]][]=[[['Contract amount',money(data.contractAmount)],['Status',data.contractStatus]],[['Fiscal year',data.fiscalYear],['Procurement category',data.procurementCategory]],[['Procurement method',data.procurementMethod],['Public entity',data.publicEntityName]],[['Contract location',data.contractAddress],['Joint venture',data.jointVentureName]],[['Beneficial owner',data.beneficialOwner],['Source',data.sourceDataset]]];return <Layout><Button asChild variant="ghost" size="sm" className="mb-5"><Link to="/contractors"><ArrowLeft className="h-4 w-4"/>Contractors</Link></Button><header className="border-b border-slate-200 pb-6"><div className="flex flex-wrap items-center gap-2"><Badge variant="secondary">{data.contractStatus??"Status unavailable"}</Badge><span className="font-mono text-xs text-slate-500">{data.contractCode}</span></div><h1 className="mt-3 max-w-4xl text-2xl font-semibold tracking-[-.025em] text-slate-950">{data.contractName}</h1></header><div className="mt-6 grid gap-8 lg:grid-cols-[minmax(0,1fr)_320px]"><main><h2 className="text-base font-semibold text-slate-950">Contract information</h2><dl className="mt-4 divide-y divide-slate-200 rounded-xl border border-slate-200 bg-white">{fields.map((pair,index)=><div key={index} className="grid gap-4 px-5 py-4 sm:grid-cols-2">{pair.map(([label,value])=><div key={label}><dt className="text-xs font-medium text-slate-500">{label}</dt><dd className="mt-1 text-sm text-slate-900">{String(value??"Not provided by source")}</dd></div>)}</div>)}</dl>{data.projectDescription?<section className="mt-8"><h2 className="text-base font-semibold text-slate-950">Project description</h2><p className="mt-3 max-w-3xl whitespace-pre-line text-sm leading-6 text-slate-700">{data.projectDescription}</p></section>:null}</main><aside><h2 className="text-base font-semibold text-slate-950">Contractors</h2><div className="mt-3 divide-y rounded-xl border border-slate-200 bg-white">{data.contractors.map(contractor=><Link key={contractor.id} to={`/contractors/${contractor.id}`} className="block p-4 hover:bg-slate-50"><p className="text-sm font-medium text-slate-950">{contractor.name}</p><p className="mt-1 font-mono text-xs text-slate-500">PAN {contractor.pan??"not provided"}{contractor.sharePercentage===null?"":` · ${contractor.sharePercentage}%`}</p></Link>)}</div></aside></div></Layout>}
function State({text}:{text:string}){return <div className="grid min-h-[50vh] place-items-center text-sm text-slate-600">{text}</div>}
