/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { GeoJSON, MapContainer, Pane, useMap } from "react-leaflet";
import L, { type GeoJSON as LeafletGeoJSON, type Layer } from "leaflet";
import "leaflet/dist/leaflet.css";
import Layout from "@/components/layout/Layout";
import { ArrowRight, ChevronRight, MapPinned } from "lucide-react";
import { Button } from "@/components/ui/button";
import { fetchBudgetSnapshot, fetchFiscalYears, type BudgetSnapshot } from "../api/mapBudgetApi";
import { loadProvinceGeometry, localLevelById, provinces, validUrlSelection, type GeoCollection, type MunicipalityProperties, type ProvinceOption } from "../model/geography";

type ProvinceProperties = { PROVINCE: number; PR_NAME: string };
const NEPAL_BOUNDS = L.latLngBounds([26.30, 80.00], [30.48, 88.22]);

function MapMotion({ bounds, reduced }: { bounds: L.LatLngBoundsExpression; reduced: boolean }) { const map = useMap(); useEffect(() => { if (reduced) map.fitBounds(bounds, { padding: [24, 24] }); else map.flyToBounds(bounds, { padding: [34, 34], duration: 0.9, maxZoom: 10 }); }, [map, bounds, reduced]); return null; }

function formatAmount(value: string | null) { if (value === null) return "—"; return `NPR ${new Intl.NumberFormat("en-NP", { maximumFractionDigits: 0 }).format(Number(value))}`; }

export default function OpenBudgetMap() {
  const [params, setParams] = useSearchParams();
  const [{ province, municipality }, setSelection] = useState(() => validUrlSelection(params.get("province"), params.get("municipality")));
  const [provinceGeometry, setProvinceGeometry] = useState<GeoCollection | null>(null);
  const [localGeometry, setLocalGeometry] = useState<GeoCollection | null>(null);
  const [geoStatus, setGeoStatus] = useState<"loading" | "ready" | "error">("loading");
  const [years, setYears] = useState<string[]>([]);
  const [snapshot, setSnapshot] = useState<BudgetSnapshot | null>(null);
  const [budgetStatus, setBudgetStatus] = useState<"idle" | "loading" | "ready" | "error">("idle");
  const localLayer = useRef<LeafletGeoJSON | null>(null);
  const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  const fiscalYear = params.get("fy") ?? years[0] ?? "";

  useEffect(() => { setSelection(validUrlSelection(params.get("province"), params.get("municipality"))); }, [params]);

  useEffect(() => { const controller = new AbortController(); fetch("/geo/nepal/provinces.geojson", { signal: controller.signal }).then(response => { if (!response.ok) throw new Error(); return response.json(); }).then(data => { if (data.features?.length !== 7) throw new Error(); setProvinceGeometry(data); setGeoStatus("ready"); }).catch(error => { if (error.name !== "AbortError") setGeoStatus("error"); }); return () => controller.abort(); }, []);
  useEffect(() => { const controller = new AbortController(); fetchFiscalYears(controller.signal).then(data => { const sorted = [...data].sort().reverse(); setYears(sorted); if (!params.get("fy") && sorted[0]) setParams(current => { const next = new URLSearchParams(current); next.set("fy", sorted[0]); return next; }, { replace: true }); }).catch(() => setYears([])); return () => controller.abort(); }, [params, setParams]);
  useEffect(() => { if (!province) { setLocalGeometry(null); return; } const controller = new AbortController(); setGeoStatus("loading"); loadProvinceGeometry(province, controller.signal).then(data => { setLocalGeometry(data); setGeoStatus("ready"); }).catch(error => { if (error.name !== "AbortError") setGeoStatus("error"); }); return () => controller.abort(); }, [province]);
  useEffect(() => { if (!municipality || !fiscalYear) { setSnapshot(null); setBudgetStatus("idle"); return; } const controller = new AbortController(); setBudgetStatus("loading"); fetchBudgetSnapshot(municipality.id, fiscalYear, controller.signal).then(data => { setSnapshot(data); setBudgetStatus("ready"); }).catch(error => { if (error.name !== "AbortError") setBudgetStatus("error"); }); return () => controller.abort(); }, [municipality, fiscalYear]);

  const updateSelection = (nextProvince: ProvinceOption | null, municipalityId?: string | null) => { const nextMunicipality = municipalityId ? localLevelById.get(municipalityId) ?? null : null; setSelection({ province: nextProvince, municipality: nextMunicipality }); setParams(current => { const next = new URLSearchParams(current); if (nextProvince) next.set("province", nextProvince.id); else next.delete("province"); if (nextMunicipality) next.set("municipality", nextMunicipality.id); else next.delete("municipality"); return next; }); };
  const selectedBounds = useMemo(() => { if (municipality && localGeometry) { const feature = localGeometry.features.find(item => item.properties?.municipalityId === municipality.id); if (feature) return L.geoJSON(feature).getBounds(); } if (province && provinceGeometry) { const feature = provinceGeometry.features.find(item => String(item.properties?.PROVINCE) === province.id); if (feature) return L.geoJSON(feature).getBounds(); } return NEPAL_BOUNDS; }, [municipality, province, provinceGeometry, localGeometry]);

  return <Layout><div className="space-y-5"><header><h1 className="text-2xl font-bold tracking-[-.025em] text-slate-950">Open Budget Map</h1><p className="mt-2 text-sm text-slate-600">Explore Nepal by province and local government, then open the available budget context.</p></header>
    <div className="flex flex-wrap items-center gap-1 text-sm"><button className="font-medium text-emerald-700 hover:underline" onClick={() => updateSelection(null)}>Nepal</button>{province ? <><ChevronRight className="h-4 w-4 text-slate-400"/><button className="font-medium text-emerald-700 hover:underline" onClick={() => updateSelection(province)}>{province.name}</button></> : null}{municipality ? <><ChevronRight className="h-4 w-4 text-slate-400"/><span className="text-slate-700">{municipality.nameEn}</span></> : null}</div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_320px]"><section className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="grid gap-3 border-b p-4 sm:grid-cols-2"><label className="text-xs font-medium text-slate-700">Select Province<select value={province?.id ?? ""} onChange={event => updateSelection(provinces.find(item => item.id === event.target.value) ?? null)} className="mt-1.5 block h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm"><option value="">Choose a province</option>{provinces.map(item => <option key={item.id} value={item.id}>{item.name} Province</option>)}</select></label>{province ? <label className="text-xs font-medium text-slate-700">Select Local Level<select value={municipality?.id ?? ""} onChange={event => updateSelection(province, event.target.value || null)} className="mt-1.5 block h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm"><option value="">Choose a local level</option>{[...localLevelById.values()].filter(item => item.provinceId === province.id).sort((a,b)=>a.nameEn.localeCompare(b.nameEn)).map(item => <option key={item.id} value={item.id}>{item.nameEn}</option>)}</select></label> : null}</div>
      <div className="relative h-[520px] bg-slate-100"><MapContainer bounds={NEPAL_BOUNDS} zoomControl={false} attributionControl={false} className="h-full w-full bg-slate-100" minZoom={6} maxZoom={12}><MapMotion bounds={selectedBounds} reduced={reduced}/>{provinceGeometry ? <Pane name="provinces" style={{ zIndex: 410 }}><GeoJSON data={provinceGeometry as any} style={feature => { const selected = province?.id === String((feature?.properties as ProvinceProperties).PROVINCE); return { color: selected ? "#047857" : "#64748b", weight: selected ? 3 : 1.5, fillColor: selected ? "#d1fae5" : "#e2e8f0", fillOpacity: province && !selected ? .18 : .65 }; }} onEachFeature={(feature, layer) => { const properties = feature.properties as ProvinceProperties; const current = provinces.find(item => item.id === String(properties.PROVINCE)); layer.bindTooltip(current?.name ?? properties.PR_NAME, { sticky: true, direction: "top" }); layer.on({ click: () => current && updateSelection(current), mouseover: event => event.target.setStyle({ fillColor: "#a7f3d0", fillOpacity: .85 }), mouseout: event => event.target.setStyle({ fillColor: province?.id === current?.id ? "#d1fae5" : "#e2e8f0", fillOpacity: province && province.id !== current?.id ? .18 : .65 }) }); }} /></Pane> : null}{province && localGeometry ? <Pane name="local-levels" style={{ zIndex: 430 }}><GeoJSON ref={localLayer} key={province.id} data={localGeometry as any} style={feature => { const p = feature?.properties as MunicipalityProperties; const selected = municipality?.id === p.municipalityId; return { color: selected ? "#065f46" : "#64748b", weight: selected ? 3 : .8, fillColor: selected ? "#34d399" : "#f8fafc", fillOpacity: selected ? .75 : .35 }; }} onEachFeature={(feature, layer: Layer) => { const p = feature.properties as MunicipalityProperties; layer.bindTooltip(`<strong>${p.municipalityName}</strong><br>${p.districtName} · ${p.provinceName}`, { sticky: true, direction: "top" }); layer.on({ click: () => updateSelection(province, p.municipalityId) }); }} /></Pane> : null}</MapContainer>{geoStatus === "loading" ? <div className="pointer-events-none absolute left-4 top-4 z-[500] rounded-lg bg-white px-3 py-2 text-xs font-medium text-slate-600 shadow-sm">Loading boundaries…</div> : null}{geoStatus === "error" ? <div className="absolute inset-x-4 top-4 z-[500] rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">Administrative boundaries could not be loaded. <button className="font-semibold underline" onClick={() => updateSelection(null)}>Return to Nepal</button></div> : null}</div>
      <div className="border-t px-4 py-3 text-xs text-slate-500">Administrative boundaries: Open Knowledge Nepal – Local Boundaries · CC BY 4.0</div></section>
      <aside className="rounded-xl border border-slate-200 bg-white p-5 xl:min-h-[520px]"><div className="flex items-center gap-2"><MapPinned className="h-5 w-5 text-emerald-700"/><h2 className="font-semibold text-slate-950">Budget Snapshot</h2></div>{municipality ? <><p className="mt-5 font-semibold text-slate-950">{municipality.nameEn}</p><label className="mt-4 block text-xs font-medium text-slate-600">Fiscal year<select value={fiscalYear} onChange={event => setParams(current => { const next = new URLSearchParams(current); next.set("fy", event.target.value); return next; })} className="mt-1.5 h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm">{years.map(year => <option key={year}>{year}</option>)}</select></label>{budgetStatus === "loading" ? <div className="mt-6 space-y-3">{[1,2,3,4].map(item => <div key={item} className="h-10 animate-pulse rounded bg-slate-100"/>)}</div> : budgetStatus === "error" ? <p className="mt-6 text-sm leading-6 text-red-700">Budget data could not be loaded for this local level.</p> : snapshot && snapshot.dataScope ? <dl className="mt-6 divide-y divide-slate-100">{[["Total project budget",snapshot.totalBudget],["Capital budget",snapshot.capitalBudget],["Recurrent budget",snapshot.recurrentBudget],["Project expenditure",snapshot.actualExpenditure]].map(([label,value]) => <div key={label} className="flex items-center justify-between gap-4 py-3"><dt className="text-sm text-slate-600">{label}</dt><dd className="text-sm font-semibold tabular-nums text-slate-950">{formatAmount(value)}</dd></div>)}</dl> : <p className="mt-6 text-sm leading-6 text-slate-600">Budget data is not available for this local level for FY {fiscalYear}.</p>}<Button asChild className="mt-6 w-full"><Link to={`/insights/local?municipality=${municipality.id}&fy=${encodeURIComponent(fiscalYear)}`}>View Full Budget Insights<ArrowRight className="h-4 w-4"/></Link></Button></> : <p className="mt-5 text-sm leading-6 text-slate-600">Select a province and local level to view available budget information.</p>}</aside></div>
  </div></Layout>;
}
